### PR TITLE
[GUI] Fix command parameters and error messages

### LINKED ISSUE #158: [PE-D] After adding a large number, the feedback box stops working
I've added an exercise and the feedback box is stuck

There was an exception before this when i added 999999999999999999999 exercise weight

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ongch00/ped#5

### LINKED ISSUE #159: [PE-D] Able to add exercises with 0 exercise weight, reps and sets
UserGuide mention that is must be a positive integer.

However, it is possible to add exercise with 0 of them

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ongch00/ped#4

### LINKED ISSUE #163: [PE-D] long exercise name is not text wrapped
UI long command for exercises (possibly others have not tested) cannot ve viewed fully, also with a invalid(future) date.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tharshita/ped#8

### LINKED ISSUE #166: [PE-D] invalid exercise date
exercise date can be set to before current date, invalid as it has already passed way before the person might be even born

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: tharshita/ped#5

### LINKED ISSUE #167: [PE-D] invalid address can be entered
validity of address is not checked properly, could be better! With invalid phone and email and address as seen above, person will be uncontactable 

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: tharshita/ped#4

### LINKED ISSUE #168: [PE-D] invalid phone number can be entered
validity of phone number is not checked properly, could be better! With invalid phone and email and address as seen above, person will be uncontactable 

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: tharshita/ped#3

### LINKED ISSUE #169: [PE-D] Invalid email can be entered
validity of email is not checked properly, could be better! With invalid phone and email and address as seen above, person will be uncontactable 

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: tharshita/ped#2

### LINKED ISSUE #171: [PE-D] Scheduling ANY user who already has a schedule removes existing schedules
As in title.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: gb3h/ped#5

### LINKED ISSUE #172: [PE-D] Adding exercise with invalid date 31-02-1202 adds a valid date exercise
-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: gb3h/ped#4

### LINKED ISSUE #173: [PE-D] Adding overlapping time period overwrites old schedule
If an existing person has a schedule, e.g. 1200 - 1400, adding 1330-1600 will overwrite the first one with no feedback to the user.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: gb3h/ped#3

### LINKED ISSUE #186: [PE-D] Can't enter all kinds of names
An example name in the UG has a comma but I can't enter that into the product.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: aakanksha-rai/ped#4

### LINKED ISSUE #189: [PE-D] Name formatting error
The UG describes that name of client allows a comma (as shown in the examples). But, the app doesn't allow for the same! 

Suggestion: you may want to allow use of special characters 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: raivatshah/ped#12

### LINKED ISSUE #196: [PE-D] Input validation for Sports parameter
The app allows any input, including special characters for the sports field. Most sports names won't have special characters. This can later become a problem if sports is displayed or can be confusing for the user. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: raivatshah/ped#5

### LINKED ISSUE #197: [PE-D] Incorrect error message for very high weight
Similar to issue id #1, the app shows an incorrect error message for a very high weight. A better error message maybe to say that such a high weight is not possible or something, but it is definitely not correct right now because a very large number can definitely be a whole or decimal number. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: raivatshah/ped#4

### LINKED ISSUE #200: [PE-D] Incorrect error message displayed for height
When adding a new client profile (`add-c n/john doe p/-12334454 e/hi@google.com a/22 college ave h/100000000`) the FitBiz app doesn't store the client profile. 

I am guessing that it is because there's some internal implementation that doesn't allow numbers beyond a specific range, but the error message shown is "Input height must either be whole or decimal number (eg. 165 or 155.2)". So probably needs a better error message since 100000000 is a whole number. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: raivatshah/ped#1

### PR DESCRIPTION
**Pull request by AaronCQL**
Use this PR to fix all command parameters and their error messages.

## Client
@AaronCQL @ziyingli 
- [x] fixes #200 
- [x] fixes #197 
- [x] fixes #196 
- [x] fixes #189 
- [x] fixes #186 
- [x] fixes #169 
- [x] fixes #168 
- [x] fixes #167 

## Schedule
@Dban1 @tohkerwei 
- [x] fixes #173 
- [x] fixes #171 

## Exercise
@Yonggiee 
- [x] fixes #166 
- [x] fixes #163 
- [x] fixes #159 
- [x] fixes #158 
- [x] fixes #172 

> Please add any issues that are relevant

### CODE REVIEW

File: src/main/java/seedu/address/model/exercise/ExerciseDate.java [hunk 1]
```diff
@@ -14,7 +14,8 @@
 public class ExerciseDate {
 
     public static final String MESSAGE_CONSTRAINTS =
-        "Date input should be in the format DD-MM-YYYY and it should not be blank";
+        "Date input should be in the format DD-MM-YYYY and should not be blank. "
+        + "It should only be from within one year before to the current date.";
```
Comment (AaronCQL) [inline src/main/java/seedu/address/model/exercise/ExerciseDate.java:18]: Kinda awkward phrasing. How about `The accepted range of dates is today to one year before today.`? And maybe add an `eg. 18-05-2020`

**Review by Dban1 — APPROVED** [review]
LGTM
